### ISSUE TITLE
Not working if starting shell on specified dir

### ISSUE THREAD

**Issue by bntzio** [hharnisc/hypercwd#15] opened 2017-03-06 18:49 UTC
Whenever I start a new window I want to start on the **~/code** directory.

So I have this on my **~/.zshrc** file:

`cd ~/code`

This seems to override hypercwd, any suggestions on making hypercwd work with this config?

**Comment by hharnisc** [comment] 2017-09-02 20:04
I think the ~/.zshrc is always going to win in this case, since it runs after `hyper` opens a new terminal session. However I'm working on making `hypercwd` that would allow you to configure a starting directory.

**Comment by hharnisc** [comment] 2017-09-02 20:05
Going to close this as a duplicate of #2

**Closed by hharnisc** 2017-09-02 20:05 UTC
